/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juego;

import Juego.Menu;

/**
 *
 * @author fampa
 */
public class Configuracion extends javax.swing.JFrame {

    Menu menu;
    ConfiguracionJava config;
    Tablero_Sequence tablero;
    
    public Configuracion(Menu menu) {
        initComponents();
        this.menu = menu;
//        setAmount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidad_jugadores = new javax.swing.JLabel();
        two = new javax.swing.JRadioButton();
        three = new javax.swing.JRadioButton();
        four = new javax.swing.JRadioButton();
        six = new javax.swing.JRadioButton();
        rojo = new javax.swing.JRadioButton();
        color_fichas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        eight = new javax.swing.JRadioButton();
        negro = new javax.swing.JRadioButton();
        rosado = new javax.swing.JRadioButton();
        amarillo = new javax.swing.JRadioButton();
        verde = new javax.swing.JRadioButton();
        naranja = new javax.swing.JRadioButton();
        morado = new javax.swing.JRadioButton();
        azul = new javax.swing.JRadioButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIGURACIÓN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 60));

        cantidad_jugadores.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        cantidad_jugadores.setForeground(new java.awt.Color(255, 255, 255));
        cantidad_jugadores.setText("CANTIDAD DE JUGADORES");
        getContentPane().add(cantidad_jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 270, 30));

        two.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setText("2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 210, 30));

        three.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 210, 30));

        four.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setText("4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 210, 30));

        six.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 210, 30));

        rojo.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        rojo.setForeground(new java.awt.Color(255, 255, 255));
        rojo.setText("ROJO");
        rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rojoMouseClicked(evt);
            }
        });
        getContentPane().add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, 30));

        color_fichas.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        color_fichas.setForeground(new java.awt.Color(255, 255, 255));
        color_fichas.setText("COLOR DE FICHA");
        getContentPane().add(color_fichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 270, 30));

        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 150, 40));

        eight.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        eight.setForeground(new java.awt.Color(255, 255, 255));
        eight.setText("8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 210, 30));

        negro.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        negro.setForeground(new java.awt.Color(255, 255, 255));
        negro.setText("NEGRO");
        negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negroMouseClicked(evt);
            }
        });
        getContentPane().add(negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 120, 30));

        rosado.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        rosado.setForeground(new java.awt.Color(255, 255, 255));
        rosado.setText("ROSADO");
        rosado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rosadoMouseClicked(evt);
            }
        });
        getContentPane().add(rosado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 30));

        amarillo.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        amarillo.setForeground(new java.awt.Color(255, 255, 255));
        amarillo.setText("AMARILLO");
        amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amarilloMouseClicked(evt);
            }
        });
        getContentPane().add(amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, 30));

        verde.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        verde.setForeground(new java.awt.Color(255, 255, 255));
        verde.setText("VERDE");
        verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verdeMouseClicked(evt);
            }
        });
        getContentPane().add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 120, 30));

        naranja.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        naranja.setForeground(new java.awt.Color(255, 255, 255));
        naranja.setText("ANARANJADO");
        naranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naranjaMouseClicked(evt);
            }
        });
        getContentPane().add(naranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 160, 30));

        morado.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        morado.setForeground(new java.awt.Color(255, 255, 255));
        morado.setText("MORADO");
        morado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moradoMouseClicked(evt);
            }
        });
        getContentPane().add(morado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 120, 30));

        azul.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        azul.setForeground(new java.awt.Color(255, 255, 255));
        azul.setText("AZUL");
        azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                azulMouseClicked(evt);
            }
        });
        getContentPane().add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/configuracionpp2.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void rojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rojoMouseClicked

    }//GEN-LAST:event_rojoMouseClicked

    private void azulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_azulMouseClicked

    private void verdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verdeMouseClicked

    private void amarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amarilloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_amarilloMouseClicked

    private void rosadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rosadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rosadoMouseClicked

    private void negroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_negroMouseClicked

    private void moradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moradoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moradoMouseClicked

    private void naranjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naranjaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_naranjaMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        config.CantJugadores = 2;
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        config.CantJugadores = 3;
    }//GEN-LAST:event_threeMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        config.CantJugadores = 4;
    }//GEN-LAST:event_fourMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        config.CantJugadores = 6;
    }//GEN-LAST:event_sixMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        config.CantJugadores = 8;
    }//GEN-LAST:event_eightMouseClicked

    public void setAmount() {
        if (config.CantJugadores == 2) {
            this.two.setSelected(true);
        } else {
            this.two.setSelected(false);
            
        }
        if (config.CantJugadores == 3) {
            this.three.setSelected(true);
        } else {
            this.three.setSelected(false);
        }

        if (config.CantJugadores == 4) {
            this.four.setSelected(true);
        } else {
            this.four.setSelected(false);
        }

        if (config.CantJugadores == 6) {
            this.six.setSelected(true);
        } else {
            this.six.setSelected(false);
        }

        if (config.CantJugadores == 8) {
            this.eight.setSelected(true);
        } else {
            this.eight.setSelected(false);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amarillo;
    private javax.swing.JRadioButton azul;
    private javax.swing.JLabel cantidad_jugadores;
    private javax.swing.JLabel color_fichas;
    private javax.swing.JRadioButton eight;
    private javax.swing.JLabel fondo;
    private javax.swing.JRadioButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton morado;
    private javax.swing.JRadioButton naranja;
    private javax.swing.JRadioButton negro;
    private javax.swing.JRadioButton rojo;
    private javax.swing.JRadioButton rosado;
    private javax.swing.JRadioButton six;
    private javax.swing.JRadioButton three;
    private javax.swing.JRadioButton two;
    private javax.swing.JRadioButton verde;
    // End of variables declaration//GEN-END:variables
}
