package Juego;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author azalia
 */
public class Juego extends javax.swing.JFrame {
    DatosUsuario datos;
    Login login;
    Menu menu;
    Usuarios usuarios;
    Date fecha= new Date();
   
 
    public Juego(Login login, DatosUsuario datos) {
        initComponents();
        this.datos = datos;
        this.login = login;
        
        //definir tamano y centrar el tablero
        this.setSize(1300, 820);
        this.setLocationRelativeTo(null);
        setVisible(true);
        
        Tablero.setLayout(new GridLayout(1,1));
        Tablero.setPreferredSize(new Dimension(900, 700));
        Tablero.add(new Tablero_Sequence(datos, login, lblTurnos, this, MazoCarta, timer, ucjlabel));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tablero = new javax.swing.JPanel();
        Eliminados = new javax.swing.JPanel();
        lblTurnos = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        ucjlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MazoCarta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SEQUENCE");
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TableroLayout = new javax.swing.GroupLayout(Tablero);
        Tablero.setLayout(TableroLayout);
        TableroLayout.setHorizontalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        TableroLayout.setVerticalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        Eliminados.setLayout(null);

        lblTurnos.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        lblTurnos.setText("Turno de: ");
        lblTurnos.setToolTipText("");
        Eliminados.add(lblTurnos);
        lblTurnos.setBounds(10, 710, 300, 40);

        timer.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        Eliminados.add(timer);
        timer.setBounds(20, 10, 190, 40);

        ucjlabel.setBackground(new java.awt.Color(150, 25, 25));
        ucjlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ucjlabel.setOpaque(true);
        Eliminados.add(ucjlabel);
        ucjlabel.setBounds(60, 140, 70, 100);

        jLabel1.setText("ULTIMA CARTA JUGADA");
        jLabel1.setOpaque(true);
        Eliminados.add(jLabel1);
        jLabel1.setBounds(30, 120, 140, 20);

        javax.swing.GroupLayout MazoCartaLayout = new javax.swing.GroupLayout(MazoCarta);
        MazoCarta.setLayout(MazoCartaLayout);
        MazoCartaLayout.setHorizontalGroup(
            MazoCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        MazoCartaLayout.setVerticalGroup(
            MazoCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MazoCarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Eliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MazoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Eliminados;
    private javax.swing.JPanel MazoCarta;
    private javax.swing.JPanel Tablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTurnos;
    private javax.swing.JLabel timer;
    private javax.swing.JLabel ucjlabel;
    // End of variables declaration//GEN-END:variables
}
