/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Juego;

import javax.swing.JOptionPane;

/**
 *
 * @author Azalia
 */
public class Menu extends javax.swing.JFrame {
    DatosUsuario datos;
    Login login;
 
  
    
   
    /**
     * Creates new form Menu
     */
    public Menu(Login login,DatosUsuario datos) {
        initComponents();
        this.setSize(818, 538);
        setLocationRelativeTo(this);
        this.login=login; 
        this.datos=datos;
     
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 36)); // NOI18N
        jLabel2.setText("-Menu sequence game-");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 130, 400, 30);

        btnConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        btnConfiguracion.setText("a)Configuracion");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion);
        btnConfiguracion.setBounds(200, 240, 260, 40);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnCerrarSesion.setText("a) Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion);
        btnCerrarSesion.setBounds(230, 370, 200, 40);

        jButton1.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 180, 160, 40);

        jButton2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jButton2.setText("Reportes");
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 300, 150, 40);

        jLabel1.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        jLabel1.setText("Miguel Medrano y Rebeca Paz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 450, 180, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menuu.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, -150, 640, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sesión?", "Confirmación de cierre de sesión", JOptionPane.OK_CANCEL_OPTION);
    if (respuesta == JOptionPane.OK_OPTION) {
        login.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Juego juego = new Juego(login,datos);
            juego.setVisible(true);            
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
